<?php
require('pages/generics.php');
require('pages/home.php');
require('pages/about.php');
require('pages/profile.php');
require('pages/tournaments.php');
require('pages/tournament-table.php');
require('pages/checkout.php');
require('pages/checkout-table.php');
require('pages/signin.php');
require('pages/members.php');
require('pages/dropbox.php');
require('pages/debate-videos.php');
require('pages/new-computer.php');
require('pages/error.php');
?>